language: node_js
node_js:
  - "13"
install:
  - yarn --ignore-engines
script:
  - yarn build
deploy:
  provider: surge
  project: ./dist/
  domain: yoursurgedomainprefix.surge.sh
  on:
    branch: master